FROM golang:1.26-bookworm@sha256:a688600ca24f8a4d3ca77f95b0dd40704a9fc787c826660eb7ba0b641b8b175d
ENV GOTOOLCHAIN=local
WORKDIR /observer
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
CMD ["go", "test", "-mod=readonly", "-race", "-count=1", "./..."]
