admissionController:
  replicas: 1
  serviceMonitor:
    enabled: true
    additionalLabels: {release: lnd-ops-monitoring}
backgroundController:
  replicas: 1
  serviceMonitor:
    enabled: true
    additionalLabels: {release: lnd-ops-monitoring}
cleanupController:
  replicas: 1
reportsController:
  replicas: 1
test:
  image:
    tag: v1.19.1
