apiVersion: v1
kind: ServiceAccount
metadata:
  name: lnd-node
automountServiceAccountToken: false
{{- if and (eq .Values.profile "regtest") .Values.bitcoin.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitcoin-node
automountServiceAccountToken: false
{{- end }}
